# Generated by Django 2.0.2 on 2018-02-20 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import festflow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only lower case alphabets are allowed.')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('problem_statement_file', models.FileField(blank=True, null=True, upload_to='problem_statements/')),
                ('venue', models.CharField(max_length=255)),
                ('venue_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('venue_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Keynote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only lower case alphabets are allowed.')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('venue', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NavbarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='#', max_length=100, validators=[festflow.models.validate_navbar_entry])),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Navbar Entry',
                'verbose_name_plural': 'Navbar Entries',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='organizerMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='avatar_images/')),
                ('contactNumber', models.CharField(max_length=15)),
                ('emailId', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactURL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
                ('degree_name', models.CharField(max_length=255)),
                ('major_subject_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('registered_events', models.ManyToManyField(to='festflow.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsor_logos/')),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
