# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('problem_statement_file', models.FileField(upload_to='problem_statements/')),
                ('venue', models.CharField(max_length=255)),
                ('venue_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('venue_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_events',
            field=models.ManyToManyField(to='festflow.Event'),
        ),
    ]
