# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0002_auto_20160827_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='problem_statement_file',
            field=models.FileField(blank=True, null=True, upload_to='problem_statements/'),
        ),
    ]
