# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0003_auto_20160827_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
