# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0004_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='identifier',
            field=models.CharField(default='none', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only lower case alphabets are allowed.')]),
            preserve_default=False,
        ),
    ]
